Real a,b,c

Inicio

escriba "sumando dos numeros ingresados por teclado"

llamar Nueva_linea
escriba "ingrese el primer numero"
lea a
escriba "ingrese el segundo numero"
lea b
c<-a+b
escriba "la suma de: ", a

llamar nueva_linea
escriba "mas: ", b

llamar nueva_linea
escriba "es: ", c

llamar nueva_linea
escriba "la suma de a que es: ", a

llamar nueva_linea
escriba "mas b que es: ", b

llamar nueva_linea
escriba "es: ", c

fin
